### ISSUE TITLE
Turret position control

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#10]
3.  Turret Position Control - develop a controller based on their model.

**Comment by devangel77b** [comment]
2.  Turret System Position Control - Levi
  a. Modify the current slides to match with what Levi has worked on.  Levi said he would take this on.  Once this is done - I will update the homework assignment accordingly.

**Comment by devriesusna** [comment]
Good evening all,

The latest code update to the simulator (sendCmdtoDcMotor.m) allows the user to simulate the behavior in a few different operational modes by specifying a "mode" of operation input to the function. The mode can be either 'step' for a step input (applied at t=1.0 seconds) or 'closed' for a closed-loop PID controller.

I've also consolidated the sendCmdtoDcMotor function so it is self-contained (all sub-functions called live in the same m-file. This way we can provide a single m-file to the students rather than a number of files.

I've updated the documentation and tried a few different test cases, but that's about it. I'm not confident that it is mid-proof yet, so before it goes live to students you might want to put it through the paces and let me know if I've missed any bugs.

Best,

Levi
