### ISSUE TITLE
Downloading the .zip from Github breaks the LFS files 

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#19]
If a student downloads the .zip direct from Github they get links to the LFS files instead of the actual files; a workaround is needed. 

If a student clones the repository using git clone or git lfs clone they get the necessary files; or if they don't have git-lfs and still use git clone it also works right; however the .zip download is a use case we want to have.

**Comment by devangel77b** [comment]
Confirmed able to recreate this on a Windows laptop. clone works but zip download direct from Github causes the links to appear as textfiles and not get the necessary resource files (such as the large .fig that are the graphics for the rooms).

**Comment by devangel77b** [comment]
Proposed workaround: When we have a release or release candidate, we should create a tagged version e.g. v20.4.1rc0  then we can zip a clone and post the resulting file e.g. corona-20.4.1rc0.zip on Google Drive for the students to get to.

**Comment by devangel77b** [comment]
Testing now. One thing I noticed is if you let it include the .git subdirectory the zip also includes all the history which can result in a large file. We really want to zip it this way:
```bash
zip -r corona-20.4.1rc0.zip corona/ -x '*.git*' 
```
to exclude the .git directory from the zip. If you don't do that last bit you get a huge 4GB file...

**Comment by kutzer** [comment]
This is unnecessary and defeats the overarching purpose of holding the code
in a git repository.



-- 
M.D.M. Kutzer, PhD
Associate Professor
Weapons, Robotics, & Control Engineering
United States Naval Academy

105 Maryland Avenue <x-apple-data-detectors://2/0>
Annapolis, MD 21402 <x-apple-data-detectors://2/0>
410.293.6113 (Phone)
410.293.2215 (Fax)
kutzer@usna.edu

https://www.usna.edu/Users/weaprcon/kutzer/
<https://www.usna.edu/Users/weaprcon/kutzer/index.php>


On Apr 1, 2020, at 10:03 PM, Dennis Evangelista <notifications@github.com>
wrote:

Proposed workaround: When we have a release or release candidate, we should
create a tagged version e.g. v20.4.1rc0 then we can zip a clone and post
the resulting file e.g. corona-20.4.1rc0.zip on Google Drive for the
students to get to.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usna-ew309/corona/issues/19#issuecomment-607578660>, or
unsubscribe

**Comment by kutzer** [comment]
Issue is solved with gitlfsFix* files.
