### ISSUE TITLE
Proposal to setup different directories for major products

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#2]
I think we need subdirectories for 
  - ballistics
  - camera view simulation (what would have been camera moving around)
  - turret movement simulation (what would have been mbed)
  - the integrated simulation

and should consider additional ones for documentation and revised report guidance.

**Comment by devangel77b** [comment]
Questions:

1.  Do we have them develop their own simulink model or provide them the framework and let them put their specific data into the blocks (i.e. G(s), Gc(s))
2.  Groups vs Individuals - since they cannot meet face to face - should we switch now to individual assignments and guidance?  I think yes since they aren't doing any hardware and it's already going to be difficult to synch up

Please let me know your thoughts.

**Comment by devriesusna** [comment]
Addressed turret movement simulation bullet

**Comment by devriesusna** [comment]
Is this addressed? Can we close this issue?

**Comment by kutzer** [comment]
Close it!



-- 
M.D.M. Kutzer, PhD
Associate Professor
Weapons, Robotics, & Control Engineering
United States Naval Academy

105 Maryland Avenue <x-apple-data-detectors://2/0>
Annapolis, MD 21402 <x-apple-data-detectors://2/0>
410.293.6113 (Phone)
410.293.2215 (Fax)
kutzer@usna.edu

https://www.usna.edu/Users/weaprcon/kutzer/
<https://www.usna.edu/Users/weaprcon/kutzer/index.php>


On Mar 25, 2020, at 8:54 PM, devriesusna <notifications@github.com> wrote:

Is this addressed? Can we close this issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usna-ew309/corona/issues/2#issuecomment-604166305>, or
unsubscribe

**Comment by devriesusna** [comment]
Closed. Addressed with reorganization of file structure.
