### ISSUE TITLE
Snap reference pictures of the room, targets, and turrets

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#3]
Do before we are locked out of space?

**Comment by devangel77b** [comment]
From @kutzer: 
As a quick side, the camera stuff I have is based on camera parameters that need to be calculated!

Can someone that is in Maury today:

(1) Grab one of my handy checkerboards from MU111 (7712#, they are at just about every lab station, and please return it when you are finished) 
(2) Grab and plug in a pico icubie
(3) Download or clone WRC_MATLABCameraSupport from GitHub and set to your MATLAB current directory
(4) Run [~,prv] = initWebcam; getCalibrationImages(prv, 15); 
(5) Follow the instructions and be sure to move the checkerboard all throughout the camera FOV at varying distances and orientations
(6) Copy the folder containing the calibration images to a shared Google Drive folder and send the link to everyone.

Who's on it?

Also, if you snap orthogonal photographs (front, top, side, bottom, back) of the iCubie with a ruler next to it I can create a nice-looking MATLAB model. You can do it with your cell phone, just try to align your camera with the face that your are photographing.

**Comment by devangel77b** [comment]
A 360 degree sweep of the room holding the camera near level should be good. If you feel like it, do both rooms but keep the images separate.

More images is usually better, so err on the side of too much, and try to stay in approximately the same position as you shoot the photos. It doesn't really matter, but from a debugging standpoint this could be useful.

**Comment by kutzer** [comment]
Also, take some long distance shots of each wall.



-- 
M.D.M. Kutzer, PhD
Associate Professor
Weapons, Robotics, & Control Engineering
United States Naval Academy

105 Maryland Avenue <x-apple-data-detectors://2/0>
Annapolis, MD 21402 <x-apple-data-detectors://2/0>
410.293.6113 (Phone)
410.293.2215 (Fax)
kutzer@usna.edu

https://www.usna.edu/Users/weaprcon/kutzer/
<https://www.usna.edu/Users/weaprcon/kutzer/index.php>


On Mar 12, 2020, at 11:49 AM, Dennis Evangelista <notifications@github.com>
wrote:

A 360 degree sweep of the room holding the camera near level should be
good. If you feel like it, do both rooms but keep the images separate.

More images is usually better, so err on the side of too much, and try to
stay in approximately the same position as you shoot the photos. It doesn't
really matter, but from a debugging standpoint this could be useful.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/usna-ew309/corona/issues/3#issuecomment-598262699>, or
unsubscribe

**Comment by devangel77b** [comment]
I got the panorama and the long distance shots of rooms, texture and object references, and iCubie orthogonal views. Also for the gun. If these look OK I will mark this task done @kutzer

**Comment by devangel77b** [comment]
The photos are here:
https://drive.google.com/drive/u/1/folders/1gsq6aWlglg-6Y8huzboswXOJwnAxE_2u

Includes
  - orthogonal views of iCubie with ruler
  - Panoramic sweeps of 78 and 80 using a D300S at 50ish and 18ish mm 
  - reference photos of near field objects like power supply scope meter
  - textures of ceiling, floor, blackboard, lights, etc

**Comment by devangel77b** [comment]
Calibration here: https://drive.google.com/drive/folders/1ar-8miVcDaPZSQ3Lkbpd-mlTkJDUY763 

There are 6 series of 30 images each. 
3 different shots with Kutzer 0.75" 6wide 7tall. 
3 different shots with Evangelista 0.02m 19wide 9tall dots.  

I put them as a subdirectory of topic 3.Computer vision in the AY20 EW309 directory.
